In [14]:
import yfinance as yf
import pandas as pd

In [15]:
df = yf.download(["MSFT", "RCL", "DIS", "PG", "AAPL", "MMM", "AXP", "BA", "LUV"], period="5y")

[*********************100%***********************]  9 of 9 completed

In [16]:
df.Close.to_csv("data/stocks_hist.csv")

In [17]:
df.Close.pct_change().cumsum()

,AAPL,AXP,BA,DIS,LUV,MMM,MSFT,PG,RCL
Date,,,,,,,,,
2018-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-23,0.000226,-0.003458,-0.007130,-0.006211,0.005702,-0.004003,0.003166,-0.030906,-0.011500
2018-01-24,-0.015703,0.010014,-0.009812,-0.005395,-0.041034,0.001599,0.002295,-0.039216,0.030082
2018-01-25,-0.033554,0.013942,0.015346,-0.004943,-0.073505,0.020454,0.007849,-0.038877,0.025705
2018-01-26,-0.031216,0.013340,0.015666,0.009892,-0.063038,0.045299,0.026587,-0.045782,0.048823
...,...,...,...,...,...,...,...,...,...
2023-01-13,1.395582,0.806948,0.189911,0.155608,-0.174926,-0.459192,1.202438,0.616282,0.371131
2023-01-17,1.404339,0.794043,0.177209,0.160739,-0.173574,-0.481662,1.207120,0.613366,0.381843
2023-01-18,1.398969,0.772385,0.167748,0.152031,-0.193553,-0.512072,1.188231,0.586577,0.351606
2023-01-19,1.399413,0.748651,0.156669,0.152435,-0.189420,-0.547266,1.171777,0.559325,0.328462
2023-01-20,1.418633,0.780997,0.155076,0.196844,-0.172685,-0.528521,1.207520,0.563187,0.364823